### ISSUE TITLE
Doesn't support start_chrome(headless=True) in new Chrome 91

### ISSUE THREAD

**Issue by dhiraz266** [mherrmann/selenium-python-helium#64] opened 2021-06-10 10:07 UTC
Hi, Helium using start_chrome(headless=True) Show This Error
```
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: headless chrome=91.0.4472.101)
```

**Comment by mherrmann** [comment] 2021-06-10 11:17
Closing as a duplicate of #61. Please use the search before opening an issue.

**Closed by mherrmann** 2021-06-10 11:17 UTC
